version: "3"
services:
  web:
    image: yakumosaki/writefreely
    volumes:
      - ./config.ini:/go/config.ini
      - ./keys:/go/keys
    ports:
      - "8080:8080"
    networks:
      - writefreely
    depends_on:
      - db
    restart: unless-stopped
  db:
    image: "mariadb:latest"
    volumes:
      - ./schema.sql:/tmp/schema.sql:ro
      - db-data:/var/lib/mysql
    networks:
      - writefreely
    environment:
      - MYSQL_DATABASE=writefreely
      - MYSQL_ROOT_PASSWORD=changeme
    restart: unless-stopped

volumes:
  web-data:
    driver_opts:
      type: none
      device: /opt/docker/writefreely/web
      o: bind
  db-data:
    driver_opts:
      type: none
      device: /opt/docker/writefreely/db
      o: bind
networks:
  writefreely:
